import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  testDir: './screenshots',
  outputDir: './output',

  use: {
    // Screenshots are taken manually in each spec via page.screenshot()
    screenshot: 'off',
    // Wait for network to settle before specs start
    waitUntil: 'networkidle',
  },

  projects: [
    {
      name: 'web',
      testDir: './screenshots/web',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.WEB_APP_URL || 'https://vault.bitwarden.com',
        // Reuse saved auth session — generated by auth/setup-auth.js
        storageState: './auth/storageState.json',
        viewport: { width: 1280, height: 800 },
        // Organization GUID — set ORG_ID in .env to override
        orgId: process.env.ORG_ID || '',
      },
    },

    // Future clients — uncomment and configure as needed:
    // {
    //   name: 'browser-extension',
    //   testDir: './screenshots/extension',
    //   use: { ... },
    // },
    // {
    //   name: 'desktop',
    //   testDir: './screenshots/desktop',
    //   use: { ... },
    // },
  ],
});
